name: Docker Image CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build And Push
      env:
        TIMESTAMP: $(date +'%Y%m%d%H')
      run: |
        docker build . -t ${{ secrets.DOCKER_USERNAME }}/registry-ui:v${{ env.TIMESTAMP }}
        docker push ${{ secrets.DOCKER_USERNAME }}/registry-ui:v${{ env.TIMESTAMP }}
